<table class="table">

  <thead>
    <tr>
        <th scope="col">Name</th>
        <th scope="col">Value</th>
    </tr>
  </thead>
  <tbody>
    <tr>
        <td>Caller Id</td>
        <td>{{$callhistory->caller_id}}</td>
    </tr>
    <tr>
        <td>Callere164</td>
        <td>{{$callhistory->callere164}}</td>
    </tr>
    <tr>
        <td>Calleraccesse164</td>
        <td>{{$callhistory->calleraccesse164}}</td>
    </tr>
    <tr>
        <td>Calleee164</td>
        <td>{{$callhistory->calleee164}}</td>
    </tr>
    <tr>
        <td>Calleeaccesse164</td>
        <td>{{$callhistory->calleeaccesse164}}</td>
    </tr>
    <tr>
        <td>Callerip</td>
        <td>{{$callhistory->callerip}}</td>
    </tr>
    <tr>
        <td>Callerproductid</td>
        <td>{{$callhistory->callerproductid}}</td>
    </tr>
    <tr>
        <td>Callertogatewaye164</td>
        <td>{{$callhistory->callertogatewaye164}}</td>
    </tr>
    <tr>
        <td>Calleeip</td>
        <td>{{$callhistory->calleeip}}</td>
    </tr>
    <tr>
        <td>calleegatewayh323 Id </td>
        <td>{{$callhistory->callergatewayh323id}}</td>
    </tr>
    <tr>
        <td>Calleeproductid</td>
        <td>{{$callhistory->calleeproductid}}</td>
    </tr>
    <tr>
        <td> Calleetogatewaye164</td>
        <td>{{$callhistory->calleetogatewaye164}}</td>
    </tr>
    <tr>
        <td>Billingmode </td>
        <td>{{$callhistory->billingmode}}</td>
    </tr>
    <tr>
        <td>Calllevel </td>
        <td>{{$callhistory->calllevel}}</td>
    </tr>
    <tr>
        <td> Agentfeetime</td>
        <td>{{$callhistory->agentfeetime}}</td>
    </tr>
    <tr>
        <td> Starttime</td>
        <td>{{$callhistory->starttime}}</td>
    </tr>
    <tr>
        <td>Stoptime </td>
        <td>{{$callhistory->stoptime}}</td>
    </tr>
    <tr>
        <td> Pdd</td>
        <td>{{$callhistory->pdd}}</td>
    </tr>
    <tr>
        <td> Holdtime</td>
        <td>{{$callhistory->holdtime}}</td>
    </tr>
    <tr>
        <td>Feeprefix</td>
        <td>{{$callhistory->feeprefix}}</td>
    </tr>
    <tr>
        <td>Feetime</td>
        <td>{{$callhistory->feetime}}</td>
    </tr>
    <tr>
        <td>Fee</td>
        <td>{{$callhistory->fee}}</td>
    </tr>
    <tr>
        <td>Suitefee</td>
        <td>{{$callhistory->suitefee}}</td>
    </tr>
    <tr>
        <td>Suitefeetime</td>
        <td>{{$callhistory->suitefeetime}}</td>
    </tr>
    <tr>
        <td>Incomefee</td>
        <td>{{$callhistory->incomefee}}</td>
    </tr>
    <tr>
        <td>Customername</td>
        <td>{{$callhistory->customername}}</td>
    </tr>
    <tr>
        <td>Agentfeeprefix</td>
        <td>{{$callhistory->agentfeeprefix}}</td>
    </tr>
    <tr>
        <td>Agentfee</td>
        <td>{{$callhistory->agentfee}}</td>
    </tr>
    <tr>
        <td>Agentsuitefee</td>
        <td>{{$callhistory->agentsuitefee}}</td>
    </tr>
    <tr>
        <td>Agentsuitefeetime</td>
        <td>{{$callhistory->agentsuitefeetime}}</td>
    </tr>
    <tr>
        <td>Agentaccount</td>
        <td>{{$callhistory->agentaccount}}</td>
    </tr>
    <tr>
        <td>Agentname</td>
        <td>{{$callhistory->agentname}}</td>
    </tr>
    <tr>
        <td>Flowno</td>
        <td>{{$callhistory->flowno}}</td>
    </tr>
    <tr>
        <td>Softswitchdn</td>
        <td>{{$callhistory->softswitchdn}}</td>
    </tr>
    <tr>
        <td>Enddirection</td>
        <td>{{$callhistory->enddirection}}</td>
    </tr>
    <tr>
        <td>Endreason</td>
        <td>{{$callhistory->endreason}}</td>
    </tr>
    <tr>
        <td>Calleebilling</td>
        <td>{{$callhistory->calleebilling}}</td>
    </tr>
    <tr>
        <td>Cdrlevel</td>
        <td>{{$callhistory->cdrlevel}}</td>
    </tr>
    <tr>
        <td>Subcdr Id</td>
        <td>{{$callhistory->subcdr_id}}</td>
    </tr>
  </tbody>
</table>
