<table class="table">

  <thead>
    <tr>
        <th scope="col">Name</th>
        <th scope="col">Value</th>
    </tr>
  </thead>
  <tbody>
    <tr>
        <td>Caller Id</td>
        <td>{{$callhistory->caller_id}}</td>
    </tr>
    <tr>
        <td>Callere</td>
        <td>{{$callhistory->callere164}}</td>
    </tr>
    <tr>
        <td>Calleraccesse</td>
        <td>{{$callhistory->calleraccesse164}}</td>
    </tr>
    <tr>
        <td>Calleee</td>
        <td>{{$callhistory->calleee164}}</td>
    </tr>
    <tr>
        <td>Calleeaccesse</td>
        <td>{{$callhistory->calleeaccesse164}}</td>
    </tr>
    <tr>
        <td>Callerip</td>
        <td>{{$callhistory->callerip}}</td>
    </tr>
    <tr>
        <td>Callercodec</td>
        <td>{{$callhistory->callercodec}}</td>
    </tr>
    <tr>
        <td>Callergatewayid</td>
        <td>{{$callhistory->callergatewayid}}</td>
    </tr>
    <tr>
        <td>Callerproductid</td>
        <td>{{$callhistory->callerproductid}}</td>
    </tr>
    <tr>
        <td>Callertogatewaye</td>
        <td>{{$callhistory->callertogatewaye164}}</td>
    </tr>
    <tr>
        <td>Callertype</td>
        <td>{{$callhistory->callertype}}</td>
    </tr>
    <tr>
        <td> Calleeip</td>
        <td>{{$callhistory->calleeip}}</td>
    </tr>
    <tr>
        <td>Calleecodec</td>
        <td>{{$callhistory->calleecodec}}</td>
    </tr>
    <tr>
        <td>Calleegatewayid</td>
        <td>{{$callhistory->calleegatewayid}}</td>
    </tr>
    <tr>
        <td> Calleeproductid</td>
        <td>{{$callhistory->calleeproductid}}</td>
    </tr>
    <tr>
        <td> Calleetogateway</td>
        <td>{{$callhistory->calleetogatewaye164}}</td>
    </tr>
    <tr>
        <td>Calleetype </td>
        <td>{{$callhistory->calleetype}}</td>
    </tr>
    <tr>
        <td> Billingmode</td>
        <td>{{$callhistory->billingmode}}</td>
    </tr>
    <tr>
        <td> Calllevel</td>
        <td>{{$callhistory->calllevel}}</td>
    </tr>
    <tr>
        <td>Agentfeetime</td>
        <td>{{$callhistory->agentfeetime}}</td>
    </tr>
    <tr>
        <td>Starttime</td>
        <td>{{$callhistory->starttime}}</td>
    </tr>
    <tr>
        <td>Stoptime</td>
        <td>{{$callhistory->stoptime}}</td>
    </tr>
    <tr>
        <td>Calleepdd</td>
        <td>{{$callhistory->calleepdd}}</td>
    </tr>
    <tr>
        <td>Holdtime</td>
        <td>{{$callhistory->holdtime}}</td>
    </tr>
    <tr>
        <td>Callerareacode</td>
        <td>{{$callhistory->callerareacode}}</td>
    </tr>
    <tr>
        <td>Feetime</td>
        <td>{{$callhistory->feetime}}</td>
    </tr>
    <tr>
        <td>Fee</td>
        <td>{{$callhistory->fee}}</td>
    </tr>
    <tr>
        <td>Tax</td>
        <td>{{$callhistory->tax}}</td>
    </tr>
    <tr>
        <td>Suitefee</td>
        <td>{{$callhistory->suitefee}}</td>
    </tr>
    <tr>
        <td>Suitefeetime</td>
        <td>{{$callhistory->suitefeetime}}</td>
    </tr>
    <tr>
        <td>Incomefee</td>
        <td>{{$callhistory->incomefee}}</td>
    </tr>
    <tr>
        <td>Incometax</td>
        <td>{{$callhistory->incometax}}</td>
    </tr>
    <tr>
        <td>Customeraccount</td>
        <td>{{$callhistory->customeraccount}}</td>
    </tr>
    <tr>
        <td>Customername</td>
        <td>{{$callhistory->customername}}</td>
    </tr>
    <tr>
        <td>Calleeareacode</td>
        <td>{{$callhistory->calleeareacode}}</td>
    </tr>
    <tr>
        <td>Agentfee</td>
        <td>{{$callhistory->agentfee}}</td>
    </tr>
    <tr>
        <td>Agenttax</td>
        <td>{{$callhistory->agenttax}}</td>
    </tr>
    <tr>
        <td>Agentsuitefee</td>
        <td>{{$callhistory->agentsuitefee}}</td>
    </tr>
    <tr>
        <td>Agentsuitefeetime</td>
        <td>{{$callhistory->agentsuitefeetime}}</td>
    </tr>
    <tr>
        <td>Agentaccount</td>
        <td>{{$callhistory->agentaccount}}</td>
    </tr>
    <tr>
        <td>Agentname</td>
        <td>{{$callhistory->agentname}}</td>
    </tr>
    <tr>
        <td>Flowno</td>
        <td>{{$callhistory->flowno}}</td>
    </tr>
    <tr>
        <td>Softswitchname</td>
        <td>{{$callhistory->softswitchname}}</td>
    </tr>
    <tr>
        <td>Softswitchcallid</td>
        <td>{{$callhistory->softswitchcallid}}</td>
    </tr>
    <tr>
        <td>Callercallid</td>
        <td>{{$callhistory->callercallid}}</td>
    </tr>
    <tr>
        <td>Calleecallid</td>
        <td>{{$callhistory->calleecallid}}</td>
    </tr>
    <tr>
        <td>Rtpforward</td>
        <td>{{$callhistory->rtpforward}}</td>
    </tr>
    <tr>
        <td>Endreason</td>
        <td>{{$callhistory->endreason}}</td>
    </tr>
    <tr>
        <td>Billingtype</td>
        <td>{{$callhistory->billingtype}}</td>
    </tr>
    <tr>
        <td>Cdrlevel</td>
        <td>{{$callhistory->cdrlevel}}</td>
    </tr>
    <tr>
        <td>Agentcdr_id</td>
        <td>{{$callhistory->agentcdr_id}}</td>
    </tr>
    <tr>
        <td>Transactionid</td>
        <td>{{$callhistory->transactionid}}</td>
    </tr>
    <tr>
        <td>Account</td>
        <td>{{!empty($account->account_name) ?  $account->account_name:""}}</td>
    </tr>
  </tbody>
</table>
